name: ci

on: 
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test

  cd: 
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SHH_USERNAME }}
          password: ${{ secrets.SHH_PASSWORD }}
          port: ${{ secrets.SHH_PORT }}
          script: |
            cd ~/se2/0/se2-example-backend
            git reset --hard origin/main
            git pull https://${{ secrets.CLONE_TOKEN }}@github.com/iliatzou/se2-example-backend main
            npm install
            pm2 restart example-backend-0
